MyDictionary.Web/Models/ErrorViewModel.cs
using System;

namespace MyDictionary.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MyDictionary.Web/Models/ExampleDetailDto.cs
using MyDictionary.Service.Mongo.Dtos;
using MyDictionary.Services.Dtos;
using System.Collections.Generic;

namespace MyDictionary.Web.Models
{
    public class ExampleDetailDto
    {
        public ExampleDto Example { get; set; }
        public List<WordDto> NewWords { get; set; }
    }
}

MyDictionary.Web/Models/ListExampleViewDto.cs
using MyDictionary.Services.Dtos;
using System.Collections.Generic;

namespace MyDictionary.Web.Models
{
    public class ListExampleViewDto
    {
        public IEnumerable<ExampleDto> Examples { get; set; }
    }
}

MyDictionary.Web/Models/ListWordViewDto.cs
using MyDictionary.Services.Dtos;
using System.Collections.Generic;

namespace MyDictionary.Web.Models
{
    public class ListWordViewDto
    {
        public List<NewWord> Words { get; set; }
    }
}

MyDictionary.Web/Controllers/ExampleController.cs
using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MongoDb.DataAccess.Entities;
using MyDictionary.Service.Mongo.Dtos;
using MyDictionary.Services.Dtos;
using MyDictionary.Services.Services;
using MyDictionary.Web.Cached;
using MyDictionary.Web.Models;

namespace MyDictionary.Web.Controllers
{
    public class ExampleController : Controller
    {
        private readonly ILogger<ExampleController> _logger;
        private IWordService _wordService; 
        private IExampleService _exampleService;
        private CachedService<ExampleDto> _cachedService;
        private IMapper _mapper;

        public ExampleController(ILogger<ExampleController> logger,
            IWordService wordService,
            IExampleService exampleService, 
            CachedService<ExampleDto> cachedService,
            IMapper mapper)
        {
            _logger = logger;
            _wordService = wordService;
            _exampleService = exampleService; 
            _cachedService = cachedService;
            _mapper = mapper;
        }

        public async System.Threading.Tasks.Task<IActionResult> IndexAsync()
        {
            var examples = _cachedService.GetCachedData();
            if (examples == null)
            {
                examples = _mapper.Map<IEnumerable<ExampleDto>>(await _exampleService.Filter(x => true));
                if (examples != null)
                {
                    _cachedService.SaveToCached(examples);
                }
            }
            var exampleIds = examples.Select(x => x.Id.ToString()).ToList();
            var words = await _wordService.Filter(x =>x.IsNew && x.ExampleIds.Any(id => exampleIds.Contains(id))); 
            foreach(var example in examples)
            {
                example.Words = _mapper.Map<IEnumerable<Word>, IEnumerable<WordDto>>(words.Where(x=>x.ExampleIds.Contains(example.Id))).ToList();

            }
            return View(new ListExampleViewDto
            {
                Examples = examples.OrderByDescending(x => x.CreatedAt).AsEnumerable() ?? new List<ExampleDto>()
            });
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpGet("[controller]/Detail/{exampleId}")]
        public async System.Threading.Tasks.Task<IActionResult> DetailAsync(string exampleId)
        {
            var example = await _exampleService.GetById(exampleId);
            var wordEntities = await _wordService.Filter(x => x.ExampleIds.Contains(exampleId) && x.IsNew);
            return View(new ExampleDetailDto { 
                Example = _mapper.Map<ExampleDto>(example), 
                NewWords = _mapper.Map<List<WordDto>>(wordEntities)
            });
        }

        [HttpPost("[controller]/Add")]
        public IActionResult Add([FromForm]WordAndExampleDto data)
        {
            _wordService.AddWordAndExampleAsync(data);
            _cachedService.Clear();
            return Redirect("Index");
        }

    }
}

MyDictionary.Web/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MyDictionary.Services.Dtos;
using MyDictionary.Services.Services;
using MyDictionary.Web.Cached;
using MyDictionary.Web.Models;

namespace MyDictionary.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private IWordService _wordService; 
        private CachedService<NewWord> _cachedService;
        private IMapper _mapper;
        public HomeController(ILogger<HomeController> logger,
            IWordService wordService, 
            CachedService<NewWord> cachedService,
            IMapper mapper)
        {
            _logger = logger;
            _wordService = wordService; 
            _cachedService = cachedService;
            _mapper = mapper;
        }

        public async Task<IActionResult> IndexAsync(string searchValue)
        { 
            IEnumerable<NewWord> result = _cachedService.GetCachedData();
            if (result == null)
            {
                  result = await _wordService.GetNewWords();
                _cachedService.SaveToCached(result);
            } 
            return View(new ListWordViewDto { Words = result.ToList() });
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [HttpPost]
        public async Task<bool> AddWordAsync([FromBody]AddWordDto dto)
        {
            var result = await _wordService.UpdateAsNewWordAsync(dto);
            if (result)
            {
                _cachedService.Clear();
            }
            return result;
        }
        [HttpGet]
        [Route("DeleteNewWord")]
        public async Task<bool> DeleteNewWordAsync(string wordId)
        {
            var word = await _wordService.GetById(wordId);
            if (word != null)
            {
                word.IsNew = false;
                await _wordService.Update(word);
            }
            _cachedService.Clear();
            return true;
        } 

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MyDictionary.Web/Controllers/LearningController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;

using MyDictionary.Services.Services;
using MyDictionary.Web.Cached;

namespace MyDictionary.Web.Controllers
{
    public class LearningController : Controller
    {
        private ILearningService _learningService;
        private LearningCached _learningCached;
        public LearningController(ILearningService learningService, LearningCached learningCached)
        {
            _learningService = learningService;
            _learningCached = learningCached;
        }

        public IActionResult Index()
        {
            var model = _learningCached.GetNext();
            if (model.Equals(default(KeyValuePair<string, string>)))
            {
                _learningCached.InitCached(_learningService.InitRandomParagraph());
                model = _learningCached.GetNext();
            }

            return View(model);
        }
    }
}

MyDictionary.Web/Views/Example/Add.cshtml
@{
    ViewData["Title"] = "Add";
}

<h1>Add</h1>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <form method="post" action="/example/add">
                <div class="form-group">
                    <input class="form-control" name="Url" placeholder="Url" width="400" />
                </div>
                <div class="form-group">
                    <textarea class="form-control" name="Description" placeholder="Content" rows="30" width="400"></textarea>

                </div> 
                <button class="btn btn-primary btn-block" type="submit">Add</button>
            </form>
        </div>
    </div>
</div>

MyDictionary.Web/Views/Example/Detail.cshtml
@model ExampleDetailDto
@{
    ViewData["Title"] = "Detail";
}
<h1>Detail</h1>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            @foreach (var newWord in Model.NewWords)
            {
            <span class="badge badge-success">@newWord.Name</span>
            }
        </div>
    </div><br />
    <div class="row">
        <div class="col-lg-12">
            <a href="@Model.Example.Url">Link</a>
            <input type="hidden" value="@Model.Example.Id" id="exampleId" />
            <pre style="white-space: pre-wrap;font-family:'Times New Roman'; font-size:18px"
                 onclick="getTooltip(event)"      ontouchend="getTooltip(event)"
                 >@Model.Example.Description</pre>
        </div>
        <div class="mytooltip">
            <Button class="btn btn-primary btn-sm" onclick="addWord()">Add</Button>
            <span id="description"></span>
        </div>
    </div> 
</div>

MyDictionary.Web/Views/Example/Index.cshtml
@model ListExampleViewDto
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <form action="/home/index">
                <div class="form-group mb-10">
                    <input class="form-control" name="searchValue" placeholder="Search" />
                </div>
                <div class="form-group mb-2">
                    <button class="btn btn-primary" type="submit">Search</button>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            @foreach (var example in Model.Examples)
            {
                <span style="color:red;"><a href="/Example/Detail/@example.Id">Detail</a>&emsp; @example.CreatedAt</span>
                {
                    var desLen = example.Description.Length;
                    var descript = desLen >= 200 ? example.Description.Substring(0, 200) : example.Description.Substring(0, desLen / 2);
                    <label>@descript</label><br />
                }
                @foreach (var newWord in example.Words)
                {
                    <span class="badge badge-success">@newWord.Name</span>
                }
                <br />
            }
        </div>
    </div>
</div>

MyDictionary.Web/Views/Home/Index.cshtml
@model ListWordViewDto
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <form action="/home/index">
                <div class="form-group">
                    <input class="form-control" name="searchValue" placeholder="Search" />
                </div>
                <div class="form-group">
                    <button class="btn  btn-primary" type="submit">Search</button>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Briefly</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.Words.Any())
                    {
                        @foreach (var word in Model.Words)
                        {

                            @if (word.FirstExampleSection?.Trim().Length != 0)
                            {
                                <tr>
                                    <td><b>@word.Name</b></td>
                                    <td>
                                        @word.FirstExampleSection
                                        <b>@word.Name</b>
                                        @word.SecondExampleSection
                                    </td>
                                    <td>
                                        <button type="button" onclick="deleteWord('@word.Id')" class="btn btn-default btn-sm">X</button>
                                    </td>
                                </tr>
                            }
                            else
                            {
                                <tr>
                                    <td><b>@word.Name</b></td>
                                    <td>
                                    </td>

                                </tr>

                            }
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="2">No data</td>
                        </tr>
                    }
                </tbody>

            </table>
        </div>
    </div>
</div>

MyDictionary.Web/Views/Learning/Index.cshtml
@model KeyValuePair<string, string>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <span>@Model.Key</span><button type="button" onclick="show(); return false;" class="btn btn-sm">show</button>
            <br />
            <br />
            <span style="display:none" id="hiddenContent">@Model.Value</span>
            <br />
            <form action="/learning/">
                <button type="submit">Next</button>
            </form>
        </div>
    </div>
    <script type="text/javascript">
        var disp = false;
        function show() {
            disp = !disp;
            document.getElementById("hiddenContent").style.cssText = disp ? "display:block" : "display:none";
        }
    </script>
</div>

MyDictionary.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyDictionary.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyDictionary.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Example" asp-action="Index">Samples</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Example" asp-action="Add">Add</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Learning" asp-action="Index">Learn</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MyDictionary.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>